<?php
namespace Fortifi\FontAwesome\Interfaces\Icons;

interface MedicalIcons
{
  const ALLERGIES_MED = 'fa-allergies';
  const AMBULANCE_MED = 'fa-ambulance';
  const BAND_AID = 'fa-band-aid';
  const BIOHAZARD = 'fa-biohazard';
  const BONE_MED = 'fa-bone';
  const BONG = 'fa-bong';
  const BOOK_MEDICAL = 'fa-book-medical';
  const BRAIN = 'fa-brain';
  const BRIEFCASE_MEDICAL = 'fa-briefcase-medical';
  const BURN = 'fa-burn';
  const CANNABIS = 'fa-cannabis';
  const CAPSULES = 'fa-capsules';
  const CLINIC_MEDICAL = 'fa-clinic-medical';
  const COMMENT_MEDICAL_MED = 'fa-comment-medical';
  const CRUTCH = 'fa-crutch';
  const DIAGNOSES = 'fa-diagnoses';
  const DNA = 'fa-dna';
  const FILE_MEDICAL = 'fa-file-medical';
  const FILE_MEDICAL_ALT = 'fa-file-medical-alt';
  const FILE_PRESCRIPTION = 'fa-file-prescription';
  const FIRST_AID = 'fa-first-aid';
  const HEART_MED = 'fa-heart';
  const HEARTBEAT_MED = 'fa-heartbeat';
  const HOSPITAL_MED = 'fa-hospital';
  const HOSPITAL_ALT_MED = 'fa-hospital-alt';
  const HOSPITAL_SYMBOL = 'fa-hospital-symbol';
  const ID_CARD_ALT = 'fa-id-card-alt';
  const JOINT = 'fa-joint';
  const LAPTOP_MEDICAL = 'fa-laptop-medical';
  const MICROSCOPE_MED = 'fa-microscope';
  const MORTAR_PESTLE = 'fa-mortar-pestle';
  const NOTES_MEDICAL = 'fa-notes-medical';
  const PAGER = 'fa-pager';
  const PILLS = 'fa-pills';
  const PLUS_MED = 'fa-plus';
  const POOP = 'fa-poop';
  const PRESCRIPTION_MED = 'fa-prescription';
  const PRESCRIPTION_BOTTLE = 'fa-prescription-bottle';
  const PRESCRIPTION_BOTTLE_ALT = 'fa-prescription-bottle-alt';
  const PROCEDURES = 'fa-procedures';
  const RADIATION = 'fa-radiation';
  const RADIATION_ALT = 'fa-radiation-alt';
  const SMOKING = 'fa-smoking';
  const SMOKING_BAN = 'fa-smoking-ban';
  const STAR_OF_LIFE = 'fa-star-of-life';
  const STETHOSCOPE_MED = 'fa-stethoscope';
  const SYRINGE = 'fa-syringe';
  const TABLETS = 'fa-tablets';
  const TEETH = 'fa-teeth';
  const TEETH_OPEN = 'fa-teeth-open';
  const THERMOMETER = 'fa-thermometer';
  const TOOTH = 'fa-tooth';
  const USER_MD_MED = 'fa-user-md';
  const USER_NURSE = 'fa-user-nurse';
  const VIAL = 'fa-vial';
  const VIALS = 'fa-vials';
  const WEIGHT = 'fa-weight';
  const X_RAY = 'fa-x-ray';
}
