<?php
namespace PackagedUi\FontAwesome\Interfaces\Icons;

interface UsersPeopleIcons
{
  const ACCESSIBLE_ICON_UPI = 'fa-accessible-icon';
  const ADDRESS_BOOK_UPI = 'fa-address-book';
  const ADDRESS_CARD_UPI = 'fa-address-card';
  const BABY = 'fa-baby';
  const BED_UPI = 'fa-bed';
  const BLIND_UPI = 'fa-blind';
  const CHALKBOARD_TEACHER_UPI = 'fa-chalkboard-teacher';
  const CHILD = 'fa-child';
  const FEMALE = 'fa-female';
  const FROWN_UPI = 'fa-frown';
  const HIKING_UPI = 'fa-hiking';
  const ID_BADGE_UPI = 'fa-id-badge';
  const ID_CARD_UPI = 'fa-id-card';
  const ID_CARD_ALT_UPI = 'fa-id-card-alt';
  const MALE_UPI = 'fa-male';
  const MEH_UPI = 'fa-meh';
  const PEOPLE_CARRY_UPI = 'fa-people-carry';
  const PERSON_BOOTH_UPI = 'fa-person-booth';
  const POO_UPI = 'fa-poo';
  const PORTRAIT_UPI = 'fa-portrait';
  const POWER_OFF_UPI = 'fa-power-off';
  const PRAY_UPI = 'fa-pray';
  const RESTROOM_UPI = 'fa-restroom';
  const RUNNING = 'fa-running';
  const SKATING_UPI = 'fa-skating';
  const SKIING_UPI = 'fa-skiing';
  const SKIING_NORDIC_UPI = 'fa-skiing-nordic';
  const SMILE_UPI = 'fa-smile';
  const SNOWBOARDING_UPI = 'fa-snowboarding';
  const STREET_VIEW_UPI = 'fa-street-view';
  const SWIMMER_UPI = 'fa-swimmer';
  const USER_UPI = 'fa-user';
  const USER_ALT_UPI = 'fa-user-alt';
  const USER_ALT_SLASH_UPI = 'fa-user-alt-slash';
  const USER_ASTRONAUT = 'fa-user-astronaut';
  const USER_CHECK = 'fa-user-check';
  const USER_CIRCLE_UPI = 'fa-user-circle';
  const USER_CLOCK = 'fa-user-clock';
  const USER_COG = 'fa-user-cog';
  const USER_EDIT = 'fa-user-edit';
  const USER_FRIENDS = 'fa-user-friends';
  const USER_GRADUATE_UPI = 'fa-user-graduate';
  const USER_INJURED = 'fa-user-injured';
  const USER_LOCK = 'fa-user-lock';
  const USER_MD_UPI = 'fa-user-md';
  const USER_MINUS = 'fa-user-minus';
  const USER_NINJA = 'fa-user-ninja';
  const USER_NURSE_UPI = 'fa-user-nurse';
  const USER_PLUS = 'fa-user-plus';
  const USER_SECRET_UPI = 'fa-user-secret';
  const USER_SHIELD = 'fa-user-shield';
  const USER_SLASH_UPI = 'fa-user-slash';
  const USER_TAG = 'fa-user-tag';
  const USER_TIE = 'fa-user-tie';
  const USER_TIMES = 'fa-user-times';
  const USERS = 'fa-users';
  const USERS_COG = 'fa-users-cog';
  const WALKING = 'fa-walking';
  const WHEELCHAIR_UPI = 'fa-wheelchair';
}
